# Configuration des clés API
# Remplacer les valeurs par vos propres clés API

# Clé API OpenAI (obligatoire)
OPENAI_API_KEY = "votre_cle_api_openai"

# Clé API Stability AI (optionnel)
STABILITY_API_KEY = "votre_cle_stability"

# Configuration de la base de données
DATABASE_URL = "sqlite:///dreams.db"

# Paramètres d'analyse par défaut
DEFAULT_ANALYSIS_MODEL = "gpt-4"
DEFAULT_IMAGE_MODEL = "dall-e-3"
